FROM node:18
RUN apt-get update && apt-get install -y postgresql
WORKDIR app
COPY package.json .
RUN npm install

#POSTGRESQL SETUP
WORKDIR /tmp
ARG DB_USER
ARG DB_PASS
ENV DATABASE_USER=$DB_USER
ENV DATABASE_PASS=$DB_PASS
RUN apt-get install -y net-tools vim
COPY docker/setup.sh docker/launch.sh .
USER root
RUN chmod +x setup.sh launch.sh
USER postgres
RUN ./setup.sh

USER root
#BACKEND LAUNCH
WORKDIR /app
COPY . .
EXPOSE 5002
ENTRYPOINT ["/tmp/launch.sh"]